apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1.1"
      kubernetes.io/change-cause: "Bart updated nginx to the latest"
    creationTimestamp: "2019-09-03T02:44:23Z"
    generation: 1
    labels:
      run: nginx
    name: nginx
    namespace: default
    resourceVersion: "40172"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx
    uid: 74d8835a-85d8-48e5-9255-f5bacf423a46
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: nginx
    strategy:
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 50%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: nginx
      spec:
        containers:
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2019-09-03T02:44:57Z"
      lastUpdateTime: "2019-09-03T02:44:57Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2019-09-03T02:44:23Z"
      lastUpdateTime: "2019-09-03T02:44:57Z"
      message: ReplicaSet "nginx-756c9dc9b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
