apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6","kubernetes.io/change-cause":"Bart updated nginx to the latest again"},"creationTimestamp":"2019-09-03T02:44:23Z","generation":11,"labels":{"run":"nginx"},"name":"nginx","namespace":"default","resourceVersion":"42716","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/nginx","uid":"74d8835a-85d8-48e5-9255-f5bacf423a46"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"nginx"}},"spec":{"containers":[{"image":"nginx:latest","imagePullPolicy":"IfNotPresent","name":"nginx","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2019-09-03T03:09:04Z","lastUpdateTime":"2019-09-03T03:09:04Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2019-09-03T03:15:42Z","lastUpdateTime":"2019-09-03T03:16:30Z","message":"ReplicaSet \"nginx-6dc7b9d954\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":11,"readyReplicas":3,"replicas":4,"unavailableReplicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: Bart changed replicas to 4 again
  creationTimestamp: "2019-09-03T02:44:23Z"
  generation: 12
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "43029"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx
  uid: 74d8835a-85d8-48e5-9255-f5bacf423a46
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2019-09-03T03:09:04Z"
    lastUpdateTime: "2019-09-03T03:09:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-09-03T03:15:42Z"
    lastUpdateTime: "2019-09-03T03:19:07Z"
    message: ReplicaSet "nginx-6cddc97554" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 12
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
