---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: drupal
spec:
  ports:
    - port: 5432
  selector:
    app: drupal
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres2-claim
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: drupal
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: db-username
              #value: drupal
            - name: POSTGRES_DB
              value: drupal_production
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: db-password
              #value: mypassword
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgres/data
              subPath: whatever
      volumes:
        - name: postgres
          secret:
            secretName: db-user-pass
          persistentVolumeClaim:
            claimName: postgres2-claim
